from setuptools import setup, find_packages

setup(
    name="Repo",                           # Nombre del paquete
    version="0.1.0",                                # Versión inicial
    packages=find_packages(),                       # Paquetes a incluir
    description="Un paquete pip simple de saludo",  # Breve descripción
    author="Antonia",                         # Tu nombre
    author_email="estradaantonia97@gmail.com",                 # Tu correo electrónico
    url="https://github.com/AntoniaEM/Repo",     # URL del proyecto
)